### ISSUE TITLE
引用外部脚本报错

### ISSUE THREAD

**Issue by lin12058** [AlphaFoxz/monaco-tree-editor#10]
![image](https://github.com/AlphaFoxz/monaco-tree-editor/assets/37627813/f2143cfd-5005-4c81-ac11-97c141d2382a)
importScripts('https://yuzai.github.io/base-editor/public/eslint.js');

**Comment by AlphaFoxz** [comment]
[v1.0.1]
已在新版本修复，更新即可
Fixed and released
> pnpm update monaco-tree-editor

or
> npm update monaco-tree-editor

**Comment by AlphaFoxz** [comment]
已验证
